(function(){function j(a){a=a||{};this.cursorNode=this.div_=this.text_=this.latlng_=null;this.style_=a.style||{}}function v(a){var e=0,p=0;if(a.offsetParent){do{e+=a.offsetLeft;p+=a.offsetTop;a=a.offsetParent}while(a!=null)}return{x:e,y:p}}function w(a,e){if(a.style[e])return a.style[e];else if(a.getComputedStyle)return a.getComputedStyle()[e];else if(a.currentStyle)return a.currentStyle[e];else if(window.getComputedStyle)return document.defaultView.getComputedStyle(a,null).getPropertyValue(e);return null}
j.prototype=new google.maps.OverlayView;j.prototype.onAdd=function(){var a=document.createElement("DIV");a.style.border="1px solid black";a.style.position="absolute";a.style.whiteSpace="nowrap";a.style.backgroundColor="#ffffcc";a.style.fontSize="x-small";if(this.style_)for(var e in this.style_)if(this.style_.hasOwnProperty(e))a.style[e]=this.style_[e];this.div_=a;e=this.getPanes();this.cursorNode=e.overlayLayer.parentNode;e.floatPane.appendChild(a);google.maps.event.trigger(this,"ready")};j.prototype.draw=
function(){var a=this.getProjection();if(this.latlng_){a=a.fromLatLngToDivPixel(this.latlng_);var e=this.div_;e.style.left=a.x+"px";e.style.top=a.y-20+"px";e.innerHTML=this.text_}};j.prototype.onRemove=function(){this.div_.parentNode.removeChild(this.div_);this.div_=null};j.prototype.hide=function(){if(this.div_)this.div_.style.visibility="hidden"};j.prototype.show=function(a,e){if(this.div_)this.div_.style.visibility="visible";if(a||e){this.latlng_=a||this.latlng_;this.text_=e;this.draw()}};var x=
0;google.maps.FusionTablesLayer.prototype.enableMapTips=function(a){function e(){if(!m){var d=s,g=h.getProjection(),b=g.fromLatLngToDivPixel(d);b.x-=q;b.y+=q;var c=g.fromDivPixelToLatLng(b);b.x+=q*2;b.y-=q*2;g=g.fromDivPixelToLatLng(b);c=new google.maps.LatLngBounds(c,g);c="ST_INTERSECTS("+a.geometryColumn+",RECTANGLE(LATLNG("+c.getSouthWest().lat()+","+c.getSouthWest().lng()+"),LATLNG("+c.getNorthEast().lat()+","+c.getNorthEast().lng()+")))";c=encodeURIComponent("SELECT "+a.select+" FROM "+a.from+
" WHERE "+c);m=true;google.visualization?p(d,c):y(d,c)}}function p(d,g){(new google.visualization.Query("http://www.google.com/fusiontables/gvizdata?tq="+g)).send(function(b){m=false;b=b.getDataTable();html="";var c={};if(b){var f=b.getNumberOfRows(),n=b.getNumberOfColumns();if(f>0)for(i=0;i<n;i++){html+=b.getValue(0,i)+"<br/>";f={columnName:b.getColumnLabel(i),value:b.getValue(0,i)};c[b.getColumnLabel(i)]=f}}else console&&console.log("no data");t(html,d,c)})}function y(d,g){var b=document.createElement("script"),
c="query_"+x++;b.setAttribute("src","http://fusiontables.googleusercontent.com/fusiontables/api/query?sql="+g+"&jsonCallback=fusiontips."+c);b.setAttribute("id","fusiontips."+c);window.fusiontips[c]=function(f){m=false;f=f.table;html="";var n=null;if(f){var z=f.cols.length;if(f.rows.length>0){n={};for(i=0;i<z;i++){html+=f.rows[0][i]+"<br/>";n[f.cols[i]]={columnName:f.cols[i],value:f.rows[0][i]}}}}else console&&console.log("no data");t(html,d,n);delete window.fusiontips[c];b.parentNode.removeChild(b)};
document.getElementsByTagName("head")[0].appendChild(b)}function t(d,g,b){!a.suppressMapTips&&h&&g&&d&&h.show(g,d);var c;if(c=b){var f;a:{c=k;if(c==null)f=false;else{for(f in b)if(b.hasOwnProperty(f))if(!c[f]||c[f].value!=b[f].value){f=false;break a}f=true}}c=!f}if(c){k&&google.maps.event.trigger(l,"mouseout",{row:k});google.maps.event.trigger(l,"mouseover",{infoWindowHtml:d,latLng:g,row:b})}k=b}a=a||{};var h=new j(null,null),l=this,s=null,r=null,k=null,o=null,m=false,u=v(l.getMap().getDiv()),q=a.tolerance||
6;google.maps.event.addListenerOnce(h,"ready",function(){l.mousemoveListener_=google.maps.event.addDomListener(l.getMap().getDiv(),"mousemove",function(d){if(o){window.clearTimeout(o);o=null}var g=w(h.cursorNode,"cursor");if(g!=r&&r=="pointer"){google.maps.event.trigger(l,"mouseout",{row:k});k=null;h.hide()}else if(g=="pointer"&&!m&&!o){d=d;var b=0,c=0;if(!d)d=window.event;if(d.pageX||d.pageY){b=d.pageX;c=d.pageY}else if(d.clientX||d.clientY){b=d.clientX+document.body.scrollLeft+document.documentElement.scrollLeft;
c=d.clientY+document.body.scrollTop+document.documentElement.scrollTop}d={x:b,y:c};d=new google.maps.Point(d.x-u.x,d.y-u.y);s=h.getProjection().fromContainerPixelToLatLng(d);o=window.setTimeout(e,a.delay||400)}r=g})});h.setMap(this.getMap());this.maptipOverlay_=h;window.fusiontips=window.fusiontips||{}};google.maps.FusionTablesLayer.prototype.disableMapTips=function(){if(this.maptipOverlay_){this.maptipOverlay_.setMap(null);this.maptipOverlay_=null}if(this.mousemoveListener_){google.maps.event.removeListener(this.mousemoveListener_);
this.mousemoveListener_=null}};var A=google.maps.FusionTablesLayer.prototype.setMap;google.maps.FusionTablesLayer.prototype.setMap=function(a){a==null&&this.disableMapTips();A.call(this,a)}})();
